// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    // Use DIRECT_URL for migrations (port 5432) - better for schema operations
    // Use DATABASE_URL for application runtime (port 6543 with pgbouncer) - better for concurrent queries
    url: process.env["DIRECT_URL"] || process.env["DATABASE_URL"] || "",
  },
});
